/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.embedded.hnu.main.dialog;

import java.io.File;
import javax.swing.JFileChooser;
import javax.xml.ws.Action;
import org.embedded.hnu.generator.ai.HSNNN3MLGenerator;
import org.embedded.hnu.ioconfig.ai.HN3MLIOConfig;
import org.openide.filesystems.FileUtil;

/**
 *
 * @author SeoyeonKim 2021.06.09
 */
public class N3MLAlgorithmDialog extends javax.swing.JDialog {

    public static final int H_N3ML_NM_CUBA_LIF_MODEL = 0; //*------- SyKim 2021.06.01 -------*
    public static final int H_N3ML_NM_COBA_LIF_MODEL = 1;
    public static final int H_N3ML_NM_IF_MODEL = 2;
    public static final int H_N3ML_NM_SRM_MODEL = 3;
    
    public static final int H_N3ML_A_ReSuMe = 0;
    public static final int H_N3ML_A_softLIF = 1;
    public static final int H_N3ML_A_STDP = 2;
    public static final int H_N3ML_A_BP_STDP = 3;
    public static final int H_N3ML_A_SpikeProp = 4;
    
    public static final int H_SNN = 1;
    
    public static final int H_DATA_SET_TRAINING = 0;   
    public static final int H_DATA_SET_TEST = 1; 
    
    private int hN3mlNeuronModel = 0;  //*------- SyKim 2021.06.01 -------*
    private int hN3mlAlgorithm = 0;
    
    private int hDataSetOpt = H_DATA_SET_TEST;
    
    private HN3MLIOConfig hN3mlIOConf;
    private HSNNN3MLGenerator hN3mlGen;
    
    private JFileChooser fileChooser = new JFileChooser();
    
    /**
     * Creates new form N3MLAlgorithmDialog
     */
    public N3MLAlgorithmDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        myInitComponents();
    }
    
    public N3MLAlgorithmDialog(java.awt.Frame parent, boolean modal, HSNNN3MLGenerator n3mlgen, HN3MLIOConfig n3mlIO, int neuronmodel, int algorithm, int dataopt) {
        super(parent, modal);
        hN3mlNeuronModel = neuronmodel;
        hN3mlAlgorithm = algorithm;
        hDataSetOpt = dataopt;
        hN3mlGen = n3mlgen;
        hN3mlIOConf = n3mlIO;
        initComponents();
        myInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        resumeAlgorithmPanel = new javax.swing.JPanel();
        numOfClassesLabel = new javax.swing.JLabel();
        batchSizeLabel = new javax.swing.JLabel();
        simTimesLabel = new javax.swing.JLabel();
        stepsTimeLabel = new javax.swing.JLabel();
        frameTimeLabel = new javax.swing.JLabel();
        learningRateLabel = new javax.swing.JLabel();
        numOfClassesTextField = new javax.swing.JTextField();
        batchSizeTextField = new javax.swing.JTextField();
        simTimesTextField = new javax.swing.JTextField();
        stepsTimeTextField = new javax.swing.JTextField();
        frameTimeTextField = new javax.swing.JTextField();
        learningRateTextField = new javax.swing.JTextField();
        algorithmInfoPanel = new javax.swing.JPanel();
        currentAlgorithmLabel = new javax.swing.JLabel();
        printAlgorithmLabel = new javax.swing.JLabel();
        loadDataPanel = new javax.swing.JPanel();
        dataDirLabel = new javax.swing.JLabel();
        dataDirTextField = new javax.swing.JTextField();
        dataDirBrowseButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        generateButton = new javax.swing.JButton();
        logPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        varificationLogTextArea1 = new javax.swing.JTextArea();
        softLIFAlgorithmPanel = new javax.swing.JPanel();
        batchSizeLabel1 = new javax.swing.JLabel();
        momentumLabel = new javax.swing.JLabel();
        learningRateLabel1 = new javax.swing.JLabel();
        batchSizeTextField1 = new javax.swing.JTextField();
        momentumTextField = new javax.swing.JTextField();
        learningRateTextField1 = new javax.swing.JTextField();
        numOfEpochsLabel = new javax.swing.JLabel();
        numOfEpochsTextField = new javax.swing.JTextField();
        softLIFNeuronModelPanel = new javax.swing.JPanel();
        numOfClassesLabel1 = new javax.swing.JLabel();
        numOfClassesTextField1 = new javax.swing.JTextField();
        amplitudeLabel = new javax.swing.JLabel();
        amplitudeTextField = new javax.swing.JTextField();
        tauRefLabel = new javax.swing.JLabel();
        tauRefTextField = new javax.swing.JTextField();
        tauRCLabel = new javax.swing.JLabel();
        tauRCTextField = new javax.swing.JTextField();
        sigmaTextField = new javax.swing.JTextField();
        sigmaLabel = new javax.swing.JLabel();
        gainTextField = new javax.swing.JTextField();
        gainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(495, 540));
        setResizable(false);

        resumeAlgorithmPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.resumeAlgorithmPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(numOfClassesLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.numOfClassesLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(batchSizeLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.batchSizeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(simTimesLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.simTimesLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(stepsTimeLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.stepsTimeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(frameTimeLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.frameTimeLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(learningRateLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.learningRateLabel.text")); // NOI18N

        numOfClassesTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.numOfClassesTextField.text")); // NOI18N

        batchSizeTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.batchSizeTextField.text")); // NOI18N

        simTimesTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.simTimesTextField.text")); // NOI18N

        stepsTimeTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.stepsTimeTextField.text")); // NOI18N
        stepsTimeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepsTimeTextFieldActionPerformed(evt);
            }
        });

        frameTimeTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.frameTimeTextField.text")); // NOI18N

        learningRateTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.learningRateTextField.text")); // NOI18N

        javax.swing.GroupLayout resumeAlgorithmPanelLayout = new javax.swing.GroupLayout(resumeAlgorithmPanel);
        resumeAlgorithmPanel.setLayout(resumeAlgorithmPanelLayout);
        resumeAlgorithmPanelLayout.setHorizontalGroup(
            resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumeAlgorithmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resumeAlgorithmPanelLayout.createSequentialGroup()
                        .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numOfClassesLabel)
                            .addComponent(simTimesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(resumeAlgorithmPanelLayout.createSequentialGroup()
                        .addComponent(frameTimeLabel)
                        .addGap(65, 65, 65)))
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(frameTimeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(simTimesTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numOfClassesTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stepsTimeLabel)
                    .addComponent(batchSizeLabel)
                    .addComponent(learningRateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(batchSizeTextField)
                    .addComponent(stepsTimeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(learningRateTextField))
                .addContainerGap())
        );
        resumeAlgorithmPanelLayout.setVerticalGroup(
            resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resumeAlgorithmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfClassesLabel)
                    .addComponent(numOfClassesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchSizeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batchSizeLabel))
                .addGap(18, 18, 18)
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simTimesLabel)
                    .addComponent(simTimesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stepsTimeLabel))
                .addGap(18, 18, 18)
                .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(learningRateLabel)
                        .addComponent(learningRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(resumeAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(frameTimeLabel)
                        .addComponent(frameTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        algorithmInfoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.algorithmInfoPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(currentAlgorithmLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.currentAlgorithmLabel.text")); // NOI18N

        printAlgorithmLabel.setForeground(new java.awt.Color(102, 102, 102));
        org.openide.awt.Mnemonics.setLocalizedText(printAlgorithmLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.printAlgorithmLabel.text")); // NOI18N

        javax.swing.GroupLayout algorithmInfoPanelLayout = new javax.swing.GroupLayout(algorithmInfoPanel);
        algorithmInfoPanel.setLayout(algorithmInfoPanelLayout);
        algorithmInfoPanelLayout.setHorizontalGroup(
            algorithmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algorithmInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(currentAlgorithmLabel)
                .addGap(43, 43, 43)
                .addComponent(printAlgorithmLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        algorithmInfoPanelLayout.setVerticalGroup(
            algorithmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(algorithmInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(algorithmInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(currentAlgorithmLabel)
                    .addComponent(printAlgorithmLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.loadDataPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dataDirLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.dataDirLabel.text")); // NOI18N

        dataDirTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.dataDirTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(dataDirBrowseButton, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.dataDirBrowseButton.text")); // NOI18N
        dataDirBrowseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDirBrowseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadDataPanelLayout = new javax.swing.GroupLayout(loadDataPanel);
        loadDataPanel.setLayout(loadDataPanelLayout);
        loadDataPanelLayout.setHorizontalGroup(
            loadDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataDirLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dataDirBrowseButton)
                .addContainerGap())
        );
        loadDataPanelLayout.setVerticalGroup(
            loadDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loadDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataDirLabel)
                    .addComponent(dataDirTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataDirBrowseButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.openide.awt.Mnemonics.setLocalizedText(cancelButton, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.cancelButton.text")); // NOI18N
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(generateButton, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.generateButton.text")); // NOI18N
        generateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateButtonActionPerformed(evt);
            }
        });

        logPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.logPanel1.border.title"))); // NOI18N
        logPanel1.setMaximumSize(new java.awt.Dimension(32767, 20));
        logPanel1.setPreferredSize(new java.awt.Dimension(192, 18));

        jScrollPane2.setEnabled(false);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(144, 24));
        jScrollPane2.setWheelScrollingEnabled(false);

        varificationLogTextArea1.setEditable(false);
        varificationLogTextArea1.setBackground(new java.awt.Color(240, 240, 240));
        varificationLogTextArea1.setColumns(20);
        varificationLogTextArea1.setRows(3);
        varificationLogTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        varificationLogTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        varificationLogTextArea1.setEnabled(false);
        varificationLogTextArea1.setMaximumSize(new java.awt.Dimension(2147483647, 258));
        varificationLogTextArea1.setMinimumSize(new java.awt.Dimension(164, 58));
        varificationLogTextArea1.setPreferredSize(new java.awt.Dimension(142, 42));
        varificationLogTextArea1.setRequestFocusEnabled(false);
        jScrollPane2.setViewportView(varificationLogTextArea1);

        javax.swing.GroupLayout logPanel1Layout = new javax.swing.GroupLayout(logPanel1);
        logPanel1.setLayout(logPanel1Layout);
        logPanel1Layout.setHorizontalGroup(
            logPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        logPanel1Layout.setVerticalGroup(
            logPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addContainerGap())
        );

        softLIFAlgorithmPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.softLIFAlgorithmPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(batchSizeLabel1, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.batchSizeLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(momentumLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.momentumLabel.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(learningRateLabel1, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.learningRateLabel1.text")); // NOI18N

        batchSizeTextField1.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.batchSizeTextField1.text")); // NOI18N

        momentumTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.momentumTextField.text")); // NOI18N

        learningRateTextField1.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.learningRateTextField1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(numOfEpochsLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.numOfEpochsLabel.text")); // NOI18N

        numOfEpochsTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.numOfEpochsTextField.text")); // NOI18N

        javax.swing.GroupLayout softLIFAlgorithmPanelLayout = new javax.swing.GroupLayout(softLIFAlgorithmPanel);
        softLIFAlgorithmPanel.setLayout(softLIFAlgorithmPanelLayout);
        softLIFAlgorithmPanelLayout.setHorizontalGroup(
            softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softLIFAlgorithmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, softLIFAlgorithmPanelLayout.createSequentialGroup()
                        .addComponent(batchSizeLabel1)
                        .addGap(80, 80, 80))
                    .addGroup(softLIFAlgorithmPanelLayout.createSequentialGroup()
                        .addComponent(numOfEpochsLabel)
                        .addGap(9, 9, 9)))
                .addGroup(softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(numOfEpochsTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(batchSizeTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                .addGroup(softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(softLIFAlgorithmPanelLayout.createSequentialGroup()
                        .addGap(18, 19, Short.MAX_VALUE)
                        .addComponent(learningRateLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addComponent(learningRateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(softLIFAlgorithmPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(momentumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(momentumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        softLIFAlgorithmPanelLayout.setVerticalGroup(
            softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softLIFAlgorithmPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfEpochsLabel)
                    .addComponent(numOfEpochsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(momentumLabel)
                    .addComponent(momentumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(softLIFAlgorithmPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batchSizeLabel1)
                    .addComponent(batchSizeTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(learningRateLabel1)
                    .addComponent(learningRateTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        softLIFNeuronModelPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.softLIFNeuronModelPanel.border.title"))); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(numOfClassesLabel1, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.numOfClassesLabel1.text")); // NOI18N

        numOfClassesTextField1.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.numOfClassesTextField1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(amplitudeLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.amplitudeLabel.text")); // NOI18N

        amplitudeTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.amplitudeTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(tauRefLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.tauRefLabel.text")); // NOI18N

        tauRefTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.tauRefTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(tauRCLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.tauRCLabel.text")); // NOI18N

        tauRCTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.tauRCTextField.text")); // NOI18N

        sigmaTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.sigmaTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(sigmaLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.sigmaLabel.text")); // NOI18N

        gainTextField.setText(org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.gainTextField.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(gainLabel, org.openide.util.NbBundle.getMessage(N3MLAlgorithmDialog.class, "N3MLAlgorithmDialog.gainLabel.text")); // NOI18N

        javax.swing.GroupLayout softLIFNeuronModelPanelLayout = new javax.swing.GroupLayout(softLIFNeuronModelPanel);
        softLIFNeuronModelPanel.setLayout(softLIFNeuronModelPanelLayout);
        softLIFNeuronModelPanelLayout.setHorizontalGroup(
            softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softLIFNeuronModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numOfClassesLabel1)
                    .addComponent(tauRefLabel)
                    .addComponent(gainLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(tauRefTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gainTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numOfClassesTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amplitudeLabel)
                    .addComponent(tauRCLabel)
                    .addComponent(sigmaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, softLIFNeuronModelPanelLayout.createSequentialGroup()
                        .addComponent(amplitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, softLIFNeuronModelPanelLayout.createSequentialGroup()
                        .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sigmaTextField)
                            .addComponent(tauRCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        softLIFNeuronModelPanelLayout.setVerticalGroup(
            softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(softLIFNeuronModelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numOfClassesLabel1)
                    .addComponent(numOfClassesTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amplitudeLabel)
                    .addComponent(amplitudeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tauRefLabel)
                    .addComponent(tauRefTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tauRCLabel)
                    .addComponent(tauRCTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(softLIFNeuronModelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gainLabel)
                    .addComponent(gainTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sigmaLabel)
                    .addComponent(sigmaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(generateButton)
                        .addGap(57, 57, 57)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                            .addComponent(softLIFAlgorithmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(resumeAlgorithmPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loadDataPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(algorithmInfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(softLIFNeuronModelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(algorithmInfoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadDataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resumeAlgorithmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(softLIFAlgorithmPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(softLIFNeuronModelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(generateButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dataDirBrowseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDirBrowseButtonActionPerformed
        // TODO add your handling code here:
        selectDirectory(evt);
    }//GEN-LAST:event_dataDirBrowseButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        cancel();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void stepsTimeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepsTimeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stepsTimeTextFieldActionPerformed

    private void generateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateButtonActionPerformed
        initIOConf();
    }//GEN-LAST:event_generateButtonActionPerformed

    
    private void myInitComponents(){
        blindPanel();
        
        hN3mlGen.setModelAlgorithm(hN3mlNeuronModel, hN3mlAlgorithm);
        String printAlgorithm = "";
        
        if(hN3mlAlgorithm==H_N3ML_A_ReSuMe){
            printAlgorithm = "ReSuMe";
            resumeAlgorithmPanel.setVisible(true);
        }
        else if(hN3mlAlgorithm==H_N3ML_A_softLIF){
            printAlgorithm = "softLIF";
            if(hDataSetOpt==H_DATA_SET_TRAINING)
                softLIFAlgorithmPanel.setVisible(true);
            else
                softLIFAlgorithmPanel.setVisible(false);
            softLIFNeuronModelPanel.setVisible(true);
        }
        else if(hN3mlAlgorithm==H_N3ML_A_SpikeProp)
            printAlgorithm = "SpikeProp";
        else if(hN3mlAlgorithm==H_N3ML_A_STDP)
            printAlgorithm = "STDP";
        else if(hN3mlAlgorithm==H_N3ML_A_BP_STDP)
            printAlgorithm = "BP-STDP";
        
        printAlgorithmLabel.setText(printAlgorithm);
        
        //loadDataPanel.setVisible(false);
    }
    
    private void blindPanel(){
        resumeAlgorithmPanel.setVisible(false);
        softLIFAlgorithmPanel.setVisible(false);
        softLIFNeuronModelPanel.setVisible(false);
    }
    
    private void initIOConf(){
        hN3mlIOConf.setData_opt(hDataSetOpt);
        
        hN3mlIOConf.setNumofClasses(Integer.parseInt(numOfClassesTextField.getText()));
        hN3mlIOConf.setBatch_size(Integer.parseInt(batchSizeTextField.getText()));
        hN3mlIOConf.setSimulationTime(Integer.parseInt(simTimesTextField.getText()));
        hN3mlIOConf.setTimeSteps(Double.parseDouble(stepsTimeTextField.getText()));
        hN3mlIOConf.setTimeFrames(Double.parseDouble(frameTimeTextField.getText()));
        hN3mlIOConf.setLearning_rate(Double.parseDouble(learningRateTextField.getText()));
        
        generateSNNN3MLSource();
        cancel();
    }
    
    private void generateSNNN3MLSource(){
        //hSNNN3mlGen = new HSNNN3MLGenerator(hN3mlIOConf, );
        hN3mlGen.hSTATE = H_SNN;
        hN3mlGen.createFile(hN3mlGen.modelDir);
        hN3mlGen.inputN3MLIO(hN3mlIOConf);
        hN3mlGen.writeN3MLGen();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(N3MLAlgorithmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(N3MLAlgorithmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(N3MLAlgorithmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(N3MLAlgorithmDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                N3MLAlgorithmDialog dialog = new N3MLAlgorithmDialog(new javax.swing.JFrame(), true);
                  dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    @Action
    public void cancel() {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel algorithmInfoPanel;
    private javax.swing.JLabel amplitudeLabel;
    private javax.swing.JTextField amplitudeTextField;
    private javax.swing.JLabel batchSizeLabel;
    private javax.swing.JLabel batchSizeLabel1;
    private javax.swing.JTextField batchSizeTextField;
    private javax.swing.JTextField batchSizeTextField1;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel currentAlgorithmLabel;
    private javax.swing.JButton dataDirBrowseButton;
    private javax.swing.JLabel dataDirLabel;
    private javax.swing.JTextField dataDirTextField;
    private javax.swing.JLabel frameTimeLabel;
    private javax.swing.JTextField frameTimeTextField;
    private javax.swing.JLabel gainLabel;
    private javax.swing.JTextField gainTextField;
    private javax.swing.JButton generateButton;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel learningRateLabel;
    private javax.swing.JLabel learningRateLabel1;
    private javax.swing.JTextField learningRateTextField;
    private javax.swing.JTextField learningRateTextField1;
    private javax.swing.JPanel loadDataPanel;
    private javax.swing.JPanel logPanel1;
    private javax.swing.JLabel momentumLabel;
    private javax.swing.JTextField momentumTextField;
    private javax.swing.JLabel numOfClassesLabel;
    private javax.swing.JLabel numOfClassesLabel1;
    private javax.swing.JTextField numOfClassesTextField;
    private javax.swing.JTextField numOfClassesTextField1;
    private javax.swing.JLabel numOfEpochsLabel;
    private javax.swing.JTextField numOfEpochsTextField;
    private javax.swing.JLabel printAlgorithmLabel;
    private javax.swing.JPanel resumeAlgorithmPanel;
    private javax.swing.JLabel sigmaLabel;
    private javax.swing.JTextField sigmaTextField;
    private javax.swing.JLabel simTimesLabel;
    private javax.swing.JTextField simTimesTextField;
    private javax.swing.JPanel softLIFAlgorithmPanel;
    private javax.swing.JPanel softLIFNeuronModelPanel;
    private javax.swing.JLabel stepsTimeLabel;
    private javax.swing.JTextField stepsTimeTextField;
    private javax.swing.JLabel tauRCLabel;
    private javax.swing.JTextField tauRCTextField;
    private javax.swing.JLabel tauRefLabel;
    private javax.swing.JTextField tauRefTextField;
    private javax.swing.JTextArea varificationLogTextArea1;
    // End of variables declaration//GEN-END:variables

    public void selectDirectory(java.awt.event.ActionEvent evt) {
        String title="Select Project Location";
        String path = "";
        
        
        FileUtil.preventFileChooserSymlinkTraversal(fileChooser, null);
        fileChooser.setDialogTitle(title);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        path = dataDirTextField.getText();
        
        if (path.length() > 0) {
            File f = new File(path);
            if (f.exists()) {
                fileChooser.setSelectedFile(f);
            }
        }
        if (JFileChooser.APPROVE_OPTION == fileChooser.showOpenDialog(this)) {
            File projectDir = fileChooser.getSelectedFile();
            System.out.println("N3ML DataDir : "+projectDir);
            
            dataDirTextField.setText(FileUtil.normalizeFile(projectDir).getAbsolutePath());
         
        }
    }
}
